### ISSUE TITLE
Runtime error again

### ISSUE THREAD

**Issue by zxdawn** [opengeos/streamlit-geospatial#121]
```
Runtime error
2023-06-09 04:34:55.527 INFO    matplotlib.font_manager: generated new fontManager
Traceback (most recent call last):
  File "/home/user/.local/bin/streamlit", line 5, in <module>
    from streamlit.web.cli import main
  File "/home/user/.local/lib/python3.10/site-packages/streamlit/__init__.py", line 55, in <module>
    from streamlit.delta_generator import DeltaGenerator as _DeltaGenerator
  File "/home/user/.local/lib/python3.10/site-packages/streamlit/delta_generator.py", line 45, in <module>
    from streamlit.elements.arrow_altair import ArrowAltairMixin
  File "/home/user/.local/lib/python3.10/site-packages/streamlit/elements/arrow_altair.py", line 36, in <module>
    from altair.vegalite.v4.api import Chart
ModuleNotFoundError: No module named 'altair.vegalite.v4'
```

**Comment by giswqs** [comment]
https://huggingface.co/spaces/giswqs/Streamlit
